#!/usr/bin/env python3
"""Torch-free RVC voice-conversion worker (issue #144, P1 of the RVC chain).

Ephemeral per-job worker. Loads the #143-exported ONNX models + faiss index ONCE
(module globals, warm across every block), then services a stdin/stdout line loop,
converting one WAV per line until EOF, then exits -> 0 idle RAM. This is the shared
engine the future Go decorator (#145) drives as a subprocess; this file owns only
the Python worker. Invoked via `scripts/rvc` (which activates .venv-rvc).

Engine-faithful reproduction of PILOT_REPORT §4 DSP
(research/rvc-voice-conversion-integration/pilot-evidence/PILOT_REPORT.md). No
DSP redesign — every magic constant cites its §4.x subsection.

═══════════════════════════════════════════════════════════════════════════════
WIRE PROTOCOL (v1) — the load-bearing public surface #145 binds to
═══════════════════════════════════════════════════════════════════════════════
Read stdin line by line. Each line is shlex-split into EXACTLY 5 positional
tokens:

    <in> <out> <voice> <index_rate> <pitch>

  <in>          path to a source WAV (any sr/channels; decoded + resampled to 16k)
  <out>         path to write the 40 kHz mono s16le result WAV (written atomically)
  <voice>       one of the roster slugs: cool-jahns | confident-neal
  <index_rate>  float in [0.0, 1.0] — faiss retrieval blend; AUTHORITATIVE per line
  <pitch>       int; MUST be 0 in phase one (non-zero is rejected, no transpose)

RESPONSES — exactly ONE physical line per request (response count == request count):

  OK <out>                      success; the WAV now exists at <out>
  ERR <category> <message>      recoverable per-line failure; the loop continues

  <category> is a CLOSED set:
      bad-args | bad-voice | read-failed | infer-failed | write-failed
  <message> has all newlines/CRs collapsed to spaces and is capped at 300 chars,
  so an ERR is ALWAYS a single line (framing #145 relies on). A newline/CR-bearing
  <in> or <out> is REJECTED up front as `ERR bad-args` (paths must be single-line),
  so the `OK <out>` line echoes the REAL written path VERBATIM — the OK name and the
  file on disk can never diverge.

  #145 branches retryable-vs-fatal on the <category> token alone, without parsing
  the free-text message. An unknown category (forward-compat) is treated as fatal.

FRAMING / FORWARD-COMPAT: the 5-token line is positional and append-only — never
reorder or repurpose a token. Future capability (e.g. non-zero pitch, windowing)
is a trailing optional token with an engine-faithful default. The ERR category
set is append-only.

PROCESS SEMANTICS:
  EOF on stdin                  -> clean exit 0 (models freed, 0 idle RAM)
  BrokenPipeError writing out   -> clean exit 0 (the parent closed the pipe)
  MemoryError / catchable fatal -> stderr + NONZERO exit (NOT a per-block ERR)
  missing shared artifact,      -> stderr + NONZERO exit (startup fatal)
    torch present, bad venv
  native fault (segfault)       -> process dies with a nonzero signal exit
    (uncatchable in Python; documented, relied upon)

Models load once. A `LOAD <kind> <slug>` line is printed to stderr exactly once
per (kind, voice) — proof of warm-load-once across a multi-block batch.

ENV SWITCHES (both first-class, default OFF):
  OMP_NUM_THREADS=1   -> single-thread mode: ORT intra_op_num_threads=1
                         (pre-wired fallback for the faiss+ORT OpenMP-contention
                         case; default is ORT multithreaded, safe because torch —
                         the other libomp — is never imported).
  RVC_SEED=<int>      -> seed numpy RNG at startup so the external net_g flow noise
                         (`rnd`) is deterministic. Used by `make rvc-parity` so the
                         full-pipeline log-mel gate is reproducible, not flaky. The
                         SECOND, internal net_g RandomNormalLike (NSF sine dither,
                         std ~0.003) is generated by onnxruntime per run and is NOT
                         seedable from Python — it is the ~0.0009-RMS parity floor,
                         well inside the 0.98 log-mel corr gate.

DEFERRED (documented, NOT shipped): a `--mmap` model-load flag. Full-load is the
sole shipped path and what parity judges (review S7). Do not add a half-wired flag.

Timeouts (60s/block, 10min/wall) are the Go caller's (#145) job, not the worker's.

See scripts/rvc-README for install + failure-mode reference.
"""

from __future__ import annotations

import argparse
import os
import sys

import numpy as np
import onnxruntime as ort
import soundfile as sf
import soxr
from scipy import signal

# librosa + faiss are heavy; import at module load so the torch-free assertion
# below sees every inference dependency's transitive imports.
import librosa
import faiss

# ── Process exit codes (sysexits.h) — the Go caller (#145) branches on these ───
# Startup/construction fatal (missing shared artifact, torch present, bad venv):
# the worker never serviced a request. Runtime fatal (MemoryError mid-loop): a
# catchable fatal that is NOT a per-block ERR. Both are stable + nonzero.
EXIT_FATAL_STARTUP = 78   # EX_CONFIG — environment/construction is wrong
EXIT_FATAL_RUNTIME = 70   # EX_SOFTWARE — catchable runtime fatal (e.g. MemoryError)

# ── Torch-free invariant (PILOT_REPORT §1, non-negotiable) ────────────────────
# The lean .venv-rvc has no torch. If any import above transitively pulled torch,
# the guarantee is void — fail loudly at startup rather than infer under torch.
# An EXPLICIT unconditional check, NOT `assert`: `python -O` / PYTHONOPTIMIZE
# strips asserts, and this honesty invariant must never be strippable.
_TORCH_PRESENT = "torch" in sys.modules
if _TORCH_PRESENT:
    print("FATAL torch is imported at startup — the torch-free invariant is broken",
          file=sys.stderr, flush=True)
    sys.exit(EXIT_FATAL_STARTUP)


# ── Roster (kept consistent with scripts/rvc-export/_common.py voice_name()) ──
# Phase-one voices. Anything not here -> ERR bad-voice.
ROSTER = ("cool-jahns", "confident-neal")


# DUP: voice_name() is duplicated in scripts/rvc-export/_common.py (export tooling)
# and here (torch-free worker). The two run in different venvs (Applio-torch vs
# .venv-rvc), so they cannot share an import without a torch-free helper module on
# both paths; extract to a shared torch-free scripts/rvc_common.py imported by both. (tracked: #149)
def voice_name(slug: str) -> str:
    """Slug -> trained-model basename. cool-jahns -> Cool_Jahns.

    Mirrors scripts/rvc-export/_common.py voice_name() so the worker resolves
    <voice> -> <Name>.index the same way the export tooling wrote it.
    """
    return "_".join(part.capitalize() for part in slug.split("-"))


# ══════════════════════════════════════════════════════════════════════════════
# DSP core — pure functions, one per PILOT_REPORT §4 stage. No I/O, no globals.
# Each magic constant cites its §4.x subsection so the port is auditable.
# ══════════════════════════════════════════════════════════════════════════════

SR_IN = 16000            # §4: sr_in — contentvec/rmvpe operate at 16 kHz
SR_OUT = 40000           # §4: tgt — net_g emits 40 kHz directly (100 Hz frames ×400)
HOP = 160                # §4: window/hop — f0 frame hop at 16 kHz
T_PAD = 16000            # §4: x_pad 1 => t_pad 16 000 samples (reflect pad)
TRIM = 40000             # §4.7: [40000:-40000] trim on the 40 kHz output


def load_source(path: str) -> np.ndarray:
    """§4.1 Load: decode -> mono -> soxr VHQ resample to 16 kHz -> normalize.

    Returns float32 mono @ 16 kHz. Normalize peak/0.95, dividing only if >1
    (Applio: audio_max = |peak|/0.95; if audio_max > 1: audio /= audio_max).
    """
    data, sr = sf.read(path, dtype="float32", always_2d=False)
    if data.ndim > 1:                                  # mono = channel mean
        data = data.mean(axis=1)
    data = np.ascontiguousarray(data, dtype=np.float32)
    if sr != SR_IN:                                    # §4.1 soxr VHQ resample
        data = soxr.resample(data, sr, SR_IN, quality="VHQ").astype(np.float32)
    peak = float(np.abs(data).max()) if data.size else 0.0
    audio_max = peak / 0.95                            # §4.1 normalize peak/0.95
    if audio_max > 1.0:
        data = (data / audio_max).astype(np.float32)
    return data


def highpass(x: np.ndarray) -> np.ndarray:
    """§4.2 High-pass: Butterworth N=5, cutoff 48 Hz, fs 16 000, zero-phase."""
    b, a = signal.butter(N=5, Wn=48, btype="high", fs=SR_IN)   # §4.2 N=5 / 48 Hz
    return signal.filtfilt(b, a, x).astype(np.float32)         # §4.2 zero-phase filtfilt


def reflect_pad(x: np.ndarray, pad: int = T_PAD) -> np.ndarray:
    """§4.3 Reflect-pad ±16 000 samples."""
    return np.pad(x, (pad, pad), mode="reflect").astype(np.float32)


# --- §4.4 f0 (rmvpe) ----------------------------------------------------------
# cents_mapping baked constant (§4.4): 20·arange(360)+1997.3794084376191, padded
# (4,4) to length 368 for the ±4-bin weighted-average decode.
_CENTS_MAPPING = np.pad(
    20.0 * np.arange(360) + 1997.3794084376191, (4, 4)  # §4.4
).astype(np.float64)

# Coarse-pitch mapping bounds (§4.4): f0 50..1100 Hz -> mel -> linear 1..255.
_F0_MIN = 50.0
_F0_MAX = 1100.0
_F0_MEL_MIN = 1127.0 * np.log(1.0 + _F0_MIN / 700.0)     # §4.4 f0_mel=1127·ln(1+f0/700)
_F0_MEL_MAX = 1127.0 * np.log(1.0 + _F0_MAX / 700.0)


def _rmvpe_mel(x_padded: np.ndarray, melbasis: np.ndarray) -> np.ndarray:
    """§4.4 mel front-end: STFT (n_fft 1024/hop 160/win 1024, Hann-periodic,
    center reflect) -> |STFT| -> melbasis @ mag -> log(clip(mel, 1e-5)).

    Returns log-mel [128, F] for the rmvpe ONNX net.
    """
    stft = librosa.stft(                                # §4.4 STFT
        x_padded,
        n_fft=1024,
        hop_length=HOP,
        win_length=1024,
        window="hann",                                  # §4.4 librosa 'hann' == periodic
        center=True,
        pad_mode="reflect",
    )
    mag = np.abs(stft).astype(np.float32)               # §4.4 magnitude = |STFT| [513, F]
    mel = melbasis.astype(np.float32) @ mag             # §4.4 melbasis[128,513] @ mag
    log_mel = np.log(np.clip(mel, 1e-5, None))          # §4.4 log(clip(mel, 1e-5))
    return log_mel.astype(np.float32)


def _decode_f0(salience: np.ndarray, thred: float = 0.03) -> np.ndarray:
    """§4.4 decode: weighted average of cents_mapping over ±4 bins around argmax,
    then f0 = 10·2^(cents/1200); salience ≤ 0.03 -> 0."""
    center = np.argmax(salience, axis=1)                          # §4.4 argmax per frame
    padded = np.pad(salience, ((0, 0), (4, 4)))                  # §4.4 pad (4,4)
    center = center + 4
    starts = center - 4
    ends = center + 5
    todo_sal = np.stack([padded[i, starts[i]:ends[i]] for i in range(padded.shape[0])])
    todo_cents = np.stack([_CENTS_MAPPING[starts[i]:ends[i]] for i in range(padded.shape[0])])
    product_sum = np.sum(todo_sal * todo_cents, axis=1)          # §4.4 weighted avg
    weight_sum = np.sum(todo_sal, axis=1)
    cents = product_sum / weight_sum
    maxx = np.max(padded, axis=1)
    cents[maxx <= thred] = 0.0                                    # §4.4 salience ≤ 0.03 -> 0
    f0 = 10.0 * (2.0 ** (cents / 1200.0))                        # §4.4 f0 = 10·2^(cents/1200)
    f0[f0 == 10.0] = 0.0                                          # cents==0 -> unvoiced
    return f0.astype(np.float64)


def _coarse_f0(f0: np.ndarray) -> np.ndarray:
    """§4.4 coarse: f0_mel = 1127·ln(1+f0/700), linear-map to 1..255, rint."""
    f0_mel = 1127.0 * np.log(1.0 + f0 / 700.0)                   # §4.4
    voiced = f0_mel > 0
    f0_mel[voiced] = (f0_mel[voiced] - _F0_MEL_MIN) * 254.0 / (_F0_MEL_MAX - _F0_MEL_MIN) + 1.0
    f0_mel[f0_mel <= 1] = 1.0
    f0_mel[f0_mel > 255] = 255.0
    return np.rint(f0_mel).astype(np.int64)                      # §4.4 rint -> 1..255


def f0_rmvpe(x_padded: np.ndarray, rmvpe_sess: ort.InferenceSession,
             melbasis: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """§4.4 Full f0 stage. Returns (pitch_coarse int64[F], pitchf float32[F])."""
    log_mel = _rmvpe_mel(x_padded, melbasis)                     # [128, F]
    n_frames = log_mel.shape[1]
    # §4.4 pad frames to a multiple of 32 (reflect), run rmvpe.onnx, slice back.
    target = 32 * ((n_frames - 1) // 32 + 1)
    pad_amt = target - n_frames
    if pad_amt > 0:
        log_mel = np.pad(log_mel, ((0, 0), (0, pad_amt)), mode="reflect")
    mel_in = log_mel[np.newaxis, :, :].astype(np.float32)        # [1,128,F_pad]
    salience = rmvpe_sess.run(["hidden"], {"mel": mel_in})[0][0]  # [F_pad, 360]
    salience = salience[:n_frames]                               # §4.4 slice back to n_frames
    f0 = _decode_f0(salience, thred=0.03)                        # §4.4 decode + threshold
    pitch = _coarse_f0(f0.copy())                               # coarse buckets 1..255
    pitchf = f0.astype(np.float32)                              # fine f0 (Hz)
    return pitch, pitchf


def contentvec_feats(x16k_padded: np.ndarray,
                     cv_sess: ort.InferenceSession) -> np.ndarray:
    """§4.5a contentvec: audio 16k [1,T] -> feats [Tc, 768]."""
    audio = x16k_padded[np.newaxis, :].astype(np.float32)       # [1, T_samp]
    feats = cv_sess.run(["feats"], {"audio": audio})[0][0]      # [Tc, 768]
    return feats.astype(np.float32)


def index_blend(feats: np.ndarray, index: "faiss.Index", big_npy: np.ndarray,
                index_rate: float) -> np.ndarray:
    """§4.5b Index blend: faiss IVFFlat search k=8 (L2), (1/score)² weights,
    feats = index_rate·npy + (1-index_rate)·feats."""
    if index_rate <= 0.0:                                        # blend off -> passthrough
        return feats
    query = np.ascontiguousarray(feats, dtype=np.float32)
    score, ix = index.search(query, k=8)                        # §4.5b IVFFlat k=8, L2 score
    weight = np.square(1.0 / np.maximum(score, 1e-12))          # §4.5b w = (1/score)²
    weight = weight / np.sum(weight, axis=1, keepdims=True)     # §4.5b row-normalize
    npy = np.sum(big_npy[ix] * weight[:, :, np.newaxis], axis=1)  # §4.5b Σ big_npy[ix]·w
    blended = index_rate * npy + (1.0 - index_rate) * feats     # §4.5b blend
    return blended.astype(np.float32)


def upsample_protect(feats_blended: np.ndarray, feats0: np.ndarray,
                     pitch: np.ndarray, pitchf: np.ndarray, pad_len: int,
                     protect: float = 0.33) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """§4.5c ×2 nearest upsample (np.repeat) + pitch-protect 0.33.

    Returns (phone [T,768], pitch [T], pitchf [T]) sliced to the common length.
    """
    phone = np.repeat(feats_blended, 2, axis=0)                 # §4.5c ×2 nearest = np.repeat
    phone0 = np.repeat(feats0, 2, axis=0)                       # index-free copy, same upsample
    # §4.5c p_len = min(len(pad)//160, 2·Tc); slice feats/pitch/pitchf to p_len.
    p_len = min(pad_len // HOP, phone.shape[0])
    p_len = min(p_len, pitch.shape[0], pitchf.shape[0])
    phone = phone[:p_len]
    phone0 = phone0[:p_len]
    pitch = pitch[:p_len]
    pitchf = pitchf[:p_len]
    # §4.5c pitch-protect: pitchff = 1 where pitchf>0 else 0.33.
    pitchff = np.where(pitchf > 0, 1.0, protect).astype(np.float32)[:, np.newaxis]
    phone = phone * pitchff + phone0 * (1.0 - pitchff)          # §4.5c protected blend
    return phone.astype(np.float32), pitch, pitchf


def synth(phone: np.ndarray, pitch: np.ndarray, pitchf: np.ndarray,
          netg_sess: ort.InferenceSession) -> np.ndarray:
    """§4.6 net_g: build the six inputs incl. external rnd ~ N(0,1), run, take
    audio[0,0]. Returns float32 40 kHz waveform."""
    t = phone.shape[0]
    inter_channels = 192                                        # §3 rnd = [1, 192, T]
    rnd = np.random.randn(1, inter_channels, t).astype(np.float32)  # §4.6 external flow noise
    feeds = {
        "phone": phone[np.newaxis, :, :].astype(np.float32),   # §3 [1,T,768]
        "phone_lengths": np.array([t], dtype=np.int64),         # §3 [1] = T
        "pitch": pitch[np.newaxis, :].astype(np.int64),         # §3 [1,T] coarse 1..255
        "nsff0": pitchf[np.newaxis, :].astype(np.float32),      # §3 [1,T] fine f0 Hz
        "sid": np.array([0], dtype=np.int64),                   # §3 [1] speaker id 0
        "rnd": rnd,                                             # §3 [1,192,T]
    }
    audio = netg_sess.run(["audio"], feeds)[0]                  # §4.6 [1,1,T*400] @ 40 kHz
    return audio[0, 0].astype(np.float32)


def postprocess(audio: np.ndarray) -> np.ndarray:
    """§4.7 Trim [40000:-40000]; normalize peak/0.99 if >1."""
    audio = audio[TRIM:-TRIM]                                   # §4.7 trim t_pad_tgt each end
    peak = float(np.abs(audio).max()) if audio.size else 0.0
    audio_max = peak / 0.99                                     # §4.7 normalize peak/0.99
    if audio_max > 1.0:
        audio = audio / audio_max
    return audio.astype(np.float32)


def convert(x_src16k: np.ndarray, index_rate: float, bundle: "VoiceBundle",
            shared: "Shared") -> np.ndarray:
    """Run the full §4 pipeline for one block. Pure given the loaded models.

    x_src16k is already §4.1-loaded (16k mono, normalized). Steps §4.2 .. §4.7.
    """
    x = highpass(x_src16k)                                      # §4.2
    x_pad = reflect_pad(x, T_PAD)                               # §4.3
    pitch, pitchf = f0_rmvpe(x_pad, shared.rmvpe, shared.melbasis)  # §4.4
    feats0 = contentvec_feats(x_pad, shared.contentvec)        # §4.5a (index-free copy)
    feats_blended = index_blend(feats0, bundle.index, bundle.big_npy, index_rate)  # §4.5b
    phone, pitch, pitchf = upsample_protect(                    # §4.5c
        feats_blended, feats0, pitch, pitchf, pad_len=x_pad.shape[0])
    audio = synth(phone, pitch, pitchf, bundle.netg)           # §4.6
    return postprocess(audio)                                  # §4.7


# ══════════════════════════════════════════════════════════════════════════════
# Model registry — warm-load-once. Shared (voice-independent) loaded eagerly at
# startup; per-voice bundles loaded lazily the first time a voice appears, then
# reused warm. A `LOAD <kind> <slug>` stderr line is printed exactly once each.
# ══════════════════════════════════════════════════════════════════════════════

class Shared:
    """Voice-independent models, loaded once."""

    def __init__(self, contentvec: ort.InferenceSession, rmvpe: ort.InferenceSession,
                 melbasis: np.ndarray) -> None:
        self.contentvec = contentvec
        self.rmvpe = rmvpe
        self.melbasis = melbasis


class VoiceBundle:
    """Per-voice models: net_g generator + faiss index + reconstructed vectors."""

    def __init__(self, netg: ort.InferenceSession, index: "faiss.Index",
                 big_npy: np.ndarray) -> None:
        self.netg = netg
        self.index = index
        self.big_npy = big_npy


def _session_options() -> ort.SessionOptions:
    """ORT options. Single-thread fallback (first-class, default off) wired to
    OMP_NUM_THREADS=1 for the faiss+ORT OpenMP-contention case (review S4)."""
    so = ort.SessionOptions()
    if os.environ.get("OMP_NUM_THREADS") == "1":
        so.intra_op_num_threads = 1                            # single-thread fallback
    return so


def _load_session(path: str) -> ort.InferenceSession:
    if not os.path.isfile(path):
        raise FileNotFoundError(f"missing ONNX artifact: {path}")
    return ort.InferenceSession(path, _session_options(),
                                providers=["CPUExecutionProvider"])


def load_shared(models_root: str) -> Shared:
    """Load contentvec + rmvpe ORT sessions + mel basis once. Startup-fatal if
    any shared artifact is missing (raises -> nonzero exit)."""
    shared_onnx = os.path.join(models_root, "_shared", "onnx")
    contentvec = _load_session(os.path.join(shared_onnx, "contentvec.onnx"))
    rmvpe = _load_session(os.path.join(shared_onnx, "rmvpe.onnx"))
    melbasis_path = os.path.join(shared_onnx, "rmvpe_melbasis.npy")
    if not os.path.isfile(melbasis_path):
        raise FileNotFoundError(f"missing mel basis: {melbasis_path}")
    melbasis = np.load(melbasis_path).astype(np.float32)       # baked 128×513 (§4.4)
    print("LOAD shared _shared", file=sys.stderr, flush=True)
    return Shared(contentvec, rmvpe, melbasis)


def load_voice(slug: str, models_root: str) -> VoiceBundle:
    """Lazily load one voice's net_g + faiss index + reconstructed vectors.
    Logs `LOAD net_g <slug>` / `LOAD index <slug>` exactly once (warm-load proof).
    """
    name = voice_name(slug)
    onnx_dir = os.path.join(models_root, slug, "onnx")
    netg = _load_session(os.path.join(onnx_dir, "net_g.onnx"))
    print(f"LOAD net_g {slug}", file=sys.stderr, flush=True)

    index_path = os.path.join(models_root, slug, f"{name}.index")
    if not os.path.isfile(index_path):
        raise FileNotFoundError(f"missing faiss index: {index_path}")
    index = faiss.read_index(index_path)
    # §4.5b needs big_npy[ix]. The IVFFlat index stores full vectors, so
    # reconstruct them directly (dump_index.py proves reconstruct_n works here).
    # make_direct_map() first in case the index lacks one (cheap, torch-free).
    try:
        index.make_direct_map()
    except Exception:  # noqa: BLE001 - some index types have an implicit direct map
        pass
    big_npy = index.reconstruct_n(0, index.ntotal).astype(np.float32)  # §4.5b stored vectors
    print(f"LOAD index {slug}", file=sys.stderr, flush=True)
    return VoiceBundle(netg, index, big_npy)


# ══════════════════════════════════════════════════════════════════════════════
# Protocol loop
# ══════════════════════════════════════════════════════════════════════════════

ERR_CATEGORIES = ("bad-args", "bad-voice", "read-failed", "infer-failed", "write-failed")
_MSG_CAP = 300

# Catchable fatals: NOT a per-block ERR — propagate to a nonzero process exit
# (review S4). Native segfaults are uncatchable and kill the process with a
# nonzero signal exit; that is relied on, not intercepted.
FATAL_EXC = (MemoryError,)


def _one_line(text: str) -> str:
    """Collapse newlines/CRs to spaces and cap length — guarantees a single
    physical output line (review B3)."""
    flat = " ".join(str(text).split())
    return flat[:_MSG_CAP]


def _err_line(category: str, message: str) -> str:
    # Every call site passes a literal from the closed ERR set; a miss is a worker
    # bug, not user input. Coerce to the generic in-set category rather than emit an
    # off-contract token — an EXPLICIT guard, not an `assert` that `python -O` strips.
    if category not in ERR_CATEGORIES:
        message = f"[bug: off-contract category {category!r}] {message}"
        category = "infer-failed"
    return f"ERR {category} {_one_line(message)}"


def _atomic_write_wav(audio: np.ndarray, out_path: str) -> None:
    """Write 40 kHz mono s16le WAV atomically: temp in the same dir + os.replace.
    A failed block never leaves a partial WAV at <out> (review S4)."""
    import wave
    max_int16 = 32768.0                                        # match Applio int16 scaling
    pcm = np.clip(audio * max_int16, -32768, 32767).astype(np.int16)
    out_dir = os.path.dirname(os.path.abspath(out_path))
    os.makedirs(out_dir, exist_ok=True)
    tmp_path = f"{out_path}.tmp.{os.getpid()}"
    try:
        with wave.open(tmp_path, "wb") as wav:
            wav.setnchannels(1)
            wav.setsampwidth(2)                                # 16-bit
            wav.setframerate(SR_OUT)                           # 40 kHz
            wav.writeframes(pcm.tobytes())
        os.replace(tmp_path, out_path)                         # atomic swap
    except Exception:
        # clean up the temp so a failed write leaves nothing behind
        try:
            if os.path.exists(tmp_path):
                os.remove(tmp_path)
        except OSError:
            pass
        raise


class _Worker:
    """Holds warm models; processes one request line -> one response string."""

    def __init__(self, models_root: str) -> None:
        self.models_root = models_root
        self.shared = load_shared(models_root)
        self.voices: dict[str, VoiceBundle] = {}

    def _voice(self, slug: str) -> VoiceBundle:
        bundle = self.voices.get(slug)
        if bundle is None:
            bundle = load_voice(slug, self.models_root)        # warm-load-once
            self.voices[slug] = bundle
        return bundle

    def handle(self, line: str) -> str:
        """Parse + run one request line. Returns exactly one response line.

        Raises only FATAL_EXC (MemoryError) / BrokenPipeError to the caller;
        every other failure becomes a single-line ERR (the loop survives).
        """
        import shlex

        try:
            parts = shlex.split(line)
        except ValueError as e:
            return _err_line("bad-args", f"unparseable line: {e}")

        if len(parts) != 5:
            return _err_line("bad-args",
                             f"expected 5 tokens <in> <out> <voice> <index_rate> <pitch>, got {len(parts)}")
        in_path, out_path, voice, index_rate_s, pitch_s = parts

        # --- validation (all bad-args / bad-voice) ---
        # Reject a newline/CR-bearing <in> or <out> up front (round-3 #3). A CR can
        # survive CRLF stdin; collapsing it (as _one_line does) would make the OK
        # echo name a DIFFERENT path than _atomic_write_wav wrote to. Rejecting keeps
        # the OK line free to echo the REAL path verbatim (below).
        for _label, _val in (("in", in_path), ("out", out_path)):
            if "\n" in _val or "\r" in _val:
                return _err_line("bad-args", f"<{_label}> contains a newline/CR — paths must be single-line")
        if voice not in ROSTER:
            return _err_line("bad-voice", f"unknown voice '{voice}' (roster: {', '.join(ROSTER)})")
        try:
            index_rate = float(index_rate_s)
        except ValueError:
            return _err_line("bad-args", f"index_rate '{index_rate_s}' is not a float")
        if not (0.0 <= index_rate <= 1.0):
            return _err_line("bad-args", f"index_rate {index_rate} out of range [0,1]")
        try:
            pitch = int(pitch_s)
        except ValueError:
            return _err_line("bad-args", f"pitch '{pitch_s}' is not an int")
        if pitch != 0:
            return _err_line("bad-args", "pitch must be 0 in phase one")

        # --- read (read-failed) ---
        try:
            x_src = load_source(in_path)                        # §4.1
        except FATAL_EXC:
            raise
        except Exception as e:  # noqa: BLE001 - any decode/read error -> recoverable
            return _err_line("read-failed", f"{in_path}: {e}")

        # --- infer (infer-failed). An unexpected mid-DSP exception is classified
        #     infer-failed + continue (recoverable); only FATAL_EXC exits (S4/round-2 #5).
        try:
            bundle = self._voice(voice)                        # may lazily load the voice
            audio = convert(x_src, index_rate, bundle, self.shared)  # §4.2..§4.7
        except FATAL_EXC:
            raise
        except Exception as e:  # noqa: BLE001
            return _err_line("infer-failed", f"{voice}: {e}")

        # --- write (write-failed) ---
        try:
            _atomic_write_wav(audio, out_path)
        except FATAL_EXC:
            raise
        except Exception as e:  # noqa: BLE001
            return _err_line("write-failed", f"{out_path}: {e}")

        # Echo the REAL written path verbatim. Newline/CR were rejected up front
        # (round-3 #3), so this is always a single physical line AND names exactly
        # the file _atomic_write_wav created — the OK name and the file cannot diverge.
        return f"OK {out_path}"


def _emit(response: str) -> None:
    """Print one response line + flush. BrokenPipe propagates (clean exit 0)."""
    sys.stdout.write(response + "\n")
    sys.stdout.flush()


def run_loop(worker: "_Worker") -> int:
    """Service stdin line by line until EOF. One response per input line — a blank
    line is NOT skipped (round-3 #2): it shlex-splits to 0 tokens and yields a
    natural `ERR bad-args`, preserving response-count == request-count. Returns the
    process exit code. The worker is constructed by main() so a startup/construction
    failure is caught there (round-3 #4), not mid-loop."""
    for line in sys.stdin:
        line = line.rstrip("\n")
        response = worker.handle(line)                         # exactly one line back
        _emit(response)
    return 0                                                    # EOF -> clean exit 0


def _parse_args(argv: list[str]) -> argparse.Namespace:
    ap = argparse.ArgumentParser(
        prog="rvc_worker",
        description="Torch-free RVC voice-conversion worker (stdin/stdout line loop).",
    )
    ap.add_argument(
        "--models-root",
        default=os.path.join(
            os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
            "assets", "rvc-models",
        ),
        help="root holding _shared/onnx + <slug>/onnx + <slug>/<Name>.index "
             "(default: <repo>/assets/rvc-models).",
    )
    # NOTE: no --mmap. Full-load is the sole shipped path (review S7). --mmap is a
    # documented future option only (see module docstring / scripts/rvc-README).
    return ap.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(sys.argv[1:] if argv is None else argv)

    # Torch-free banner (parity test asserts this exact line; PILOT_REPORT §1).
    print(f"torch imported at inference?: {'torch' in sys.modules}", file=sys.stderr, flush=True)

    # Startup (RVC_SEED parse + load_shared / load-once) is fatal-if-it-raises: emit
    # ONE clean FATAL line + a stable nonzero exit, never a raw traceback (round-3 #4).
    # #145 reads the nonzero exit. A malformed RVC_SEED (int() ValueError) lands in the
    # startup arm too -> FATAL + EXIT_FATAL_STARTUP, not a bare traceback + exit 1.
    # Symmetric with the MemoryError path below.
    try:
        # Optional determinism switch for the parity gate (round-2 #2). Off by default.
        seed = os.environ.get("RVC_SEED")
        if seed is not None:
            np.random.seed(int(seed))
        worker = _Worker(args.models_root)
    except FATAL_EXC as e:
        print(f"FATAL {type(e).__name__}: {_one_line(str(e))}", file=sys.stderr, flush=True)
        return EXIT_FATAL_RUNTIME
    except Exception as e:  # noqa: BLE001 — bad RVC_SEED / missing artifact / torch present / bad venv
        print(f"FATAL {type(e).__name__}: {_one_line(str(e))}", file=sys.stderr, flush=True)
        return EXIT_FATAL_STARTUP

    try:
        return run_loop(worker)
    except BrokenPipeError:
        # Parent closed the pipe — clean exit 0 (review S4). Silence the final
        # flush-on-exit BrokenPipe by redirecting stdout to devnull.
        try:
            devnull = os.open(os.devnull, os.O_WRONLY)
            os.dup2(devnull, sys.stdout.fileno())
        except OSError:
            pass
        return 0
    except FATAL_EXC as e:
        # Catchable fatal (e.g. MemoryError) -> stderr + nonzero exit, NOT ERR (S4).
        print(f"FATAL {type(e).__name__}: {_one_line(str(e))}", file=sys.stderr, flush=True)
        return EXIT_FATAL_RUNTIME


if __name__ == "__main__":
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        sys.exit(130)
